language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"

matrix:
  allow_failures:
    - php: "5.6"

services:
  - memcached

notifications:
  email: false
  irc:
    channels:
      - "irc.mysociety.org#activity"
    use_notice: true
    skip_join: true

env: TWFY_TEST_DB_HOST="127.0.0.1" TWFY_TEST_DB_USER="root" TWFY_TEST_DB_PASS="" TWFY_TEST_DB_NAME="twfy_test"

before_script:
 - ./install_dependencies.sh
 - mysql -e "create database IF NOT EXISTS twfy_test;" -uroot
 - mysql -u root twfy_test < db/schema.sql
 - php composer.phar install --dev --no-interaction --prefer-source
 - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
 - mkdir -p build/logs
 - vendor/bin/codecept run --coverage --xml

after_script:
 - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.4" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
 - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.4" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'
